/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class TelaCadastroAlbum extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroAlbum
     */
    public TelaCadastroAlbum() {
        initComponents();
    }

    public void exibirTela() {
        setVisible(true);
    }

    public void fecharTela() {
        setVisible(false);
    }

    public void adicionarAcaoBotaoCancelar(ActionListener acao) {
        btn_CancelarCadastro.addActionListener(acao);
    }

    public void adicionarAcaoBotaoEnviar(ActionListener acao) {
        btn_EnviarCadastro.addActionListener(acao);
    }

    public void adicionarAcaoBotaoCadastrarFaixas(ActionListener acao) {
        btn_CadastrarFaixa.addActionListener(acao);
    }

    public void exibirMensagem(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }

    public String getTituloAlbum() {
        return txt_titulo.getText();
    }

    public String getAnoLancamentoAlbum() {
        return txt_AnoLancamento.getText();
    }

    public void setTituloAlbum(String text) {
        txt_titulo.setText(text);
    }

    public void setAnoLancamentoAlbum(String ano) {
        txt_AnoLancamento.setText(ano);
    }

    public int exibirMensagemConfirmacao(String msg, String title) {
        return JOptionPane.showConfirmDialog(null, msg, title, JOptionPane.YES_NO_OPTION);
    }

    public boolean opcaoSelecionada(int opcao) {
        return opcao == JOptionPane.YES_OPTION;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Titulo = new javax.swing.JLabel();
        txt_AnoLancamento = new javax.swing.JTextField();
        lbl_AnoLancamento = new javax.swing.JLabel();
        btnLogo = new javax.swing.JButton();
        txt_titulo = new javax.swing.JTextField();
        btn_EnviarCadastro = new javax.swing.JButton();
        btn_CancelarCadastro = new javax.swing.JButton();
        btn_CadastrarFaixa = new javax.swing.JButton();
        lbTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Titulo.setText("Título");

        lbl_AnoLancamento.setText("Ano de Lançamento");

        btnLogo.setText("+ Adicionar Imagem \n         do Album");
        btnLogo.setToolTipText("");
        btnLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoActionPerformed(evt);
            }
        });

        txt_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tituloActionPerformed(evt);
            }
        });

        btn_EnviarCadastro.setText("Enviar");
        btn_EnviarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EnviarCadastroActionPerformed(evt);
            }
        });

        btn_CancelarCadastro.setText("Cancelar");
        btn_CancelarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarCadastroActionPerformed(evt);
            }
        });

        btn_CadastrarFaixa.setText("+ Adicionar Faixas");
        btn_CadastrarFaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarFaixaActionPerformed(evt);
            }
        });

        lbTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTitle.setText("CADASTRO DE ALBUM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_CancelarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_EnviarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lbl_Titulo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_AnoLancamento, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_AnoLancamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_CadastrarFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(lbTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbTitle)
                .addGap(32, 32, 32)
                .addComponent(btnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lbl_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lbl_AnoLancamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_AnoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btn_CadastrarFaixa)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_EnviarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CancelarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoActionPerformed

    private void txt_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tituloActionPerformed

    }//GEN-LAST:event_txt_tituloActionPerformed

    private void btn_EnviarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EnviarCadastroActionPerformed
//        System.out.println(Faixa.faixaCadastrando);
//        if (Faixa.faixaCadastrando.size() == 0) {
//            JOptionPane.showMessageDialog(null, "Para cadastrar um album é preciso cadastrar pelo menos uma musica no mesmo");
//        } else {
//            String titulo = txt_titulo.getText();
//            int anoLan = Integer.parseInt(txt_AnoLancamento.getText());
//            AlbumDAO albDao = new AlbumDAO();
//            albDao.salvarAlbum(Album.getAlbumCadastrando());
//            JOptionPane.showMessageDialog(null, "Album Cadastrado com sucesso");
//            int opcao = JOptionPane.showConfirmDialog(null, "Você deseja cadastrar outro album?", "Confirmação", JOptionPane.YES_NO_OPTION);
//            if (opcao == JOptionPane.YES_OPTION) {
//                txt_titulo.setText("");
//                txt_AnoLancamento.setText("");
//                Faixa.faixaCadastrando.clear();
//                Album.setAlbumCadastrando();
//
//            } else {
//                Faixa.faixaCadastrando.clear();
//                Album.setAlbumCadastrando();
//                this.setVisible(false);
//
//            }
//        }

    }//GEN-LAST:event_btn_EnviarCadastroActionPerformed

    private void btn_CancelarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarCadastroActionPerformed
//        Faixa.faixaCadastrando.clear();
//        this.setVisible(false);
    }//GEN-LAST:event_btn_CancelarCadastroActionPerformed

    private void btn_CadastrarFaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarFaixaActionPerformed
//        if ((txt_titulo.getText().isEmpty()) || (txt_AnoLancamento.getText().isEmpty())) {
//            JOptionPane.showMessageDialog(null, "Antes criar uma faixa, por favor preencha o nome e ano do album");
//        } else {
//            String titulo = txt_titulo.getText();
//            int anoLan = Integer.parseInt(txt_AnoLancamento.getText());
//            Artista art = (Artista) Pessoa.getUsuarioLogado();
//            Album.setAlbumCadastrando(new Album(titulo, anoLan, art));
//
//            TelaCadastroAlbumFaixas telaCadastroAlbumsFaixas = new TelaCadastroAlbumFaixas(Album.getAlbumCadastrando());
//            telaCadastroAlbumsFaixas.setVisible(true);
//        }
    }//GEN-LAST:event_btn_CadastrarFaixaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroAlbum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogo;
    private javax.swing.JButton btn_CadastrarFaixa;
    private javax.swing.JButton btn_CancelarCadastro;
    private javax.swing.JButton btn_EnviarCadastro;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbl_AnoLancamento;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JTextField txt_AnoLancamento;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
