/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import model.table.FaixasTableModel;

/**
 *
 * @author Usuario
 */
public class TelaCadastroAlbum extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroAlbum
     */
    public TelaCadastroAlbum() {
        initComponents();
    }

    public void exibirTela() {
        setVisible(true);
    }

    public void fecharTela() {
        setVisible(false);
    }

    public void setTableModel(FaixasTableModel faixasTableModel) {
        jTable.setModel(faixasTableModel);
    }

    public void adicionarAcaoBotaoCancelar(ActionListener acao) {
        btn_CancelarCadastro.addActionListener(acao);
    }

    public void adicionarAcaoBotaoCadastrarFaixa(ActionListener acao) {
        btnAdicionarFaixas.addActionListener(acao);
    }

    public void adicionarAcaoBotaoEnviar(ActionListener acao) {
        btn_EnviarCadastro.addActionListener(acao);
    }

    public void exibirMensagem(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }

    public String getTituloAlbum() {
        return txt_titulo.getText();
    }

    public String getAnoLancamentoAlbum() {
        return txt_AnoLancamento.getText();
    }

    public void setTituloAlbum(String text) {
        txt_titulo.setText(text);
    }

    public void setAnoLancamentoAlbum(String ano) {
        txt_AnoLancamento.setText(ano);
    }

    public int exibirMensagemConfirmacao(String msg, String title) {
        return JOptionPane.showConfirmDialog(null, msg, title, JOptionPane.YES_NO_OPTION);
    }

    public boolean opcaoSelecionada(int opcao) {
        return opcao == JOptionPane.YES_OPTION;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Titulo = new javax.swing.JLabel();
        txt_AnoLancamento = new javax.swing.JTextField();
        lbl_AnoLancamento = new javax.swing.JLabel();
        btnLogo = new javax.swing.JButton();
        txt_titulo = new javax.swing.JTextField();
        btn_EnviarCadastro = new javax.swing.JButton();
        btn_CancelarCadastro = new javax.swing.JButton();
        lbTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAdicionarFaixas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Titulo.setText("Título");

        lbl_AnoLancamento.setText("Ano de Lançamento");

        btnLogo.setText("+ Adicionar Imagem \n         do Album");
        btnLogo.setToolTipText("");
        btnLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoActionPerformed(evt);
            }
        });

        txt_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tituloActionPerformed(evt);
            }
        });

        btn_EnviarCadastro.setText("Enviar");
        btn_EnviarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EnviarCadastroActionPerformed(evt);
            }
        });

        btn_CancelarCadastro.setText("Cancelar");
        btn_CancelarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarCadastroActionPerformed(evt);
            }
        });

        lbTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTitle.setText("CADASTRO DE ALBUM");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Faixas do Album");

        btnAdicionarFaixas.setText("Adicionar faixas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lbTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Titulo)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_CancelarCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_EnviarCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(txt_AnoLancamento)
                    .addComponent(lbl_AnoLancamento))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnAdicionarFaixas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbTitle)
                        .addGap(32, 32, 32)
                        .addComponent(btnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Titulo)
                            .addComponent(lbl_AnoLancamento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_AnoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_CancelarCadastro)
                            .addComponent(btn_EnviarCadastro)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdicionarFaixas)))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoActionPerformed

    private void txt_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tituloActionPerformed

    }//GEN-LAST:event_txt_tituloActionPerformed

    private void btn_EnviarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EnviarCadastroActionPerformed
//        System.out.println(Faixa.faixaCadastrando);
//        if (Faixa.faixaCadastrando.size() == 0) {
//            JOptionPane.showMessageDialog(null, "Para cadastrar um album é preciso cadastrar pelo menos uma musica no mesmo");
//        } else {
//            String titulo = txt_titulo.getText();
//            int anoLan = Integer.parseInt(txt_AnoLancamento.getText());
//            AlbumDAO albDao = new AlbumDAO();
//            albDao.salvarAlbum(Album.getAlbumCadastrando());
//            JOptionPane.showMessageDialog(null, "Album Cadastrado com sucesso");
//            int opcao = JOptionPane.showConfirmDialog(null, "Você deseja cadastrar outro album?", "Confirmação", JOptionPane.YES_NO_OPTION);
//            if (opcao == JOptionPane.YES_OPTION) {
//                txt_titulo.setText("");
//                txt_AnoLancamento.setText("");
//                Faixa.faixaCadastrando.clear();
//                Album.setAlbumCadastrando();
//
//            } else {
//                Faixa.faixaCadastrando.clear();
//                Album.setAlbumCadastrando();
//                this.setVisible(false);
//
//            }
//        }

    }//GEN-LAST:event_btn_EnviarCadastroActionPerformed

    private void btn_CancelarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarCadastroActionPerformed
//        Faixa.faixaCadastrando.clear();
//        this.setVisible(false);
    }//GEN-LAST:event_btn_CancelarCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroAlbum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarFaixas;
    private javax.swing.JButton btnLogo;
    private javax.swing.JButton btn_CancelarCadastro;
    private javax.swing.JButton btn_EnviarCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbl_AnoLancamento;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JTextField txt_AnoLancamento;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
