/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Image;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Usuario
 */
public class TelaCadastrarPessoa extends javax.swing.JFrame {

    private String caminhoImagemPerfil = "";
    
    /**
     * Creates new form TelaCadastrarPessoa
     */
    public TelaCadastrarPessoa() {
        initComponents();
    }

    public File subirImagemPerfil() {
        JFileChooser fileChooser = new JFileChooser();
        int resposta = fileChooser.showOpenDialog(null);

        if (resposta == JFileChooser.APPROVE_OPTION)
            return fileChooser.getSelectedFile();
            
        return null;
    }
    
    public void atualizarImagemPerfil(Image imagem) {
        this.btnImagemPerfil.setIcon(new ImageIcon(imagem));
        this.btnImagemPerfil.setText("");
    }
    
    public String getNomePessoa() {
        return txtName.getText();
    }

    public String getEmailPessoa() {
        return txtEmail.getText();
    }

    public String getUsuarioPessoa() {
        return txtUserName.getText();
    }

    public String getSenhaPessoa() {
        return txtSenha.getText();
    }
    
    public ButtonModel getTipoUsuario(){
        return buttonGroup2.getSelection();
    }
    
    public JRadioButton getRadioArtista(){
        return JbArtista;
    }

    public String getCaminhoImagemPerfil() {
        return caminhoImagemPerfil;
    }
    
    public void setCaminhoImagemPerfil(String caminhoImagemPerfil) {
        this.caminhoImagemPerfil = caminhoImagemPerfil;
    }
    
    public void adicionarAcaoBotaoImagemPerfil(ActionListener acao) {
        btnImagemPerfil.addActionListener(acao);
    }
    
    public void adicionarAcaoBotaoCancelar(ActionListener acao) {
        btnCancelar.addActionListener(acao);
    }
    
    public void adicionarAcaoBotaoCadastrarPessoa(ActionListener acao) {
        btnSalvar.addActionListener(acao);
    }
    
    public void exibirMensagem(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }

    public void exibirTela() {
        setVisible(true);
    }
    
     public void fecharTela(){
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        btnImagemPerfil = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        lbName = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbUserName = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        JbArtista = new javax.swing.JRadioButton();
        jbReviewer = new javax.swing.JRadioButton();
        lbPessoa = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnImagemPerfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnImagemPerfil.setText("+");
        btnImagemPerfil.setActionCommand("");
        btnImagemPerfil.setAlignmentY(0.0F);
        btnImagemPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnImagemPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnImagemPerfil.setFocusPainted(false);
        btnImagemPerfil.setFocusable(false);
        btnImagemPerfil.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnImagemPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnImagemPerfil.setIconTextGap(0);
        btnImagemPerfil.setMargin(null);
        btnImagemPerfil.setMaximumSize(null);
        btnImagemPerfil.setMinimumSize(null);
        btnImagemPerfil.setPreferredSize(null);
        btnImagemPerfil.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnSalvar.setText("Cadastrar");

        lbName.setText("Nome");

        lbEmail.setText("E-mail");

        lbUserName.setText("Usuário");

        lbSenha.setText("Senha");

        buttonGroup2.add(JbArtista);
        JbArtista.setText("Artista");

        buttonGroup2.add(jbReviewer);
        jbReviewer.setText("Reviewer");

        lbPessoa.setText("Tipo de Pessoa");

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnImagemPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbPessoa)
                            .addComponent(lbSenha)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbUserName)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEmail)
                            .addComponent(lbName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSenha)
                            .addComponent(JbArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbReviewer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnImagemPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lbSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPessoa)
                .addGap(12, 12, 12)
                .addComponent(JbArtista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbReviewer)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        btnImagemPerfil.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JbArtista;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnImagemPerfil;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton jbReviewer;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPessoa;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
